### ISSUE TITLE
Mutible errors when running base code

### ISSUE THREAD

**Issue by Owen-Whitman** [juliiaa28/ARPET#1]
Hi, I have been trying to use your code but I get these mutable errors when I try to run the program. I am using windows so I set up a virtual machine with tails and I am running the code from there. I apologize if the answer is obvious, but I am young and new to programming drones. Thank you for any help!

/usr/bin/python /home/syb/Desktop/drone2/ARPET/src/main.py -p /home/syb/Desktop/drone2/ARPET/src/MobileNetSSD_deploy.prototxt.txt -m /home/syb/Desktop/drone2/ARPET/src/MobileNetSSD_deploy.caffemodel
[INFO] Loading model...
OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "/home/syb/Desktop/drone2/ARPET/src/main.py", line 123, in <module>
    main()
  File "/home/syb/Desktop/drone2/ARPET/src/main.py", line 116, in main
    track_person = tracker.Tracker("Tracking", drone, net, frames, vmax, w, h, kp, ki, kd, args['confidence'], 80)
  File "/home/syb/Desktop/drone2/ARPET/src/tracker.py", line 26, in __init__
    self.file_tracker = open("textfiles/file_tracker" + t + ".txt", "w")
IOError: [Errno 2] No such file or directory: 'textfiles/file_tracker1.031158.txt'
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/syb/Desktop/drone2/ARPET/src/ps_drone.py", line 932, in __receiveData
    cmd = self.__Video_pipe.recv()
EOFError

**Comment by juliagarriga** [comment]
Hi, do you have the directory textfiles created? I'll have to review the code to see exactly what it is, but seeing the error it seems it is a problem when it tries to create the txt file. Thanks!

**Comment by juliagarriga** [comment]
Close this

**Comment by Ulrich-Emabou** [comment]
> Hi, do you have the directory textfiles created? I'll have to review the code to see exactly what it is, but seeing the error it seems it is a problem when it tries to create the txt file. Thanks!

I'm facing the same issue.Do we need to add a textfile directory ?

**Comment by juliagarriga** [comment]
yes @Ulrich-Emabou
